# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.105.1"

default_platform :ios

platform :ios do
  desc "Bump version and push commits to GitLab"
  lane :prepare do
    increment_build_number
    type = prompt(text: "Bump type: (major/minor/patch/none)")
    increment_version_number(bump_type: type) if type != "none"

    git_commit(path: ".", message: "Version bump to #{lane_context[:VERSION_NUMBER]}")
    lane_context[:CHANGE_LOG] = File.read("./metadata/zh-Hans/release_notes.txt")
    add_git_tag(tag: lane_context[:VERSION_NUMBER], message: lane_context[:CHANGE_LOG])
    push_to_git_remote

    # match(type: "appstore") # more information: https://codesigning.guide
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    gym(scheme: "QSCMobileV3")
    pilot(changelog: lane_context[:CHANGE_LOG], distribute_external: true)
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    gym(scheme: "QSCMobileV3")
    deliver(force: true, skip_screenshots: true, submit_for_review: true)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
